### ISSUE TITLE
The link is dead (the online archive) [CLOSED]

### ISSUE THREAD

**Issue by hosadokha** [nid666/PiracyArchive#3]
tHE online LINK to the archive that u posted is dead

**Comment by travisterrell** [comment]
The links don't appear to be dead--both of them just worked for me without issue. Also, there are 2 links--and in any case, the one on archive.org should _never_ die.

Are you potentially using an ISP or in a country which is blocking the hosts? If you've tried again and are still having problems, try going to archive.org directly to verify that you can actually access the domain at all.

**Comment by nid666** [comment]
The magnet links, archive.org links, and eye.eu links appear to be functioning. The bittorrent protocol might be blocked by your ISP. Try the site which should still be up, or try downloading from the archive.org link.

**Comment by hosadokha** [comment]
no, I meant this link "This is a copy of every post with every comment from January 1st of 2016 to March 20th of 2019 It is currently located here" (http://rpiracy.ignorelist.com/).
nevermind i dont need it anymore anyways..
